using System;
using System.Collections.Generic;
using DeiveEx.TagTree;
using UnityEngine;

public interface IDamageable
{
    HitResolveResult TakeDamage(AttackHitData attackData);
}

/// <summary>
/// Actor combat-state hub.
/// Owns health/damage, combat target acquisition, lock state, and hit-event dispatch.
/// </summary>
/// <remarks>
/// The historical ActorCombater name is kept for serialized asset and API stability.
/// </remarks>
public class ActorCombater : MonoBehaviour, IDamageable
{
    private const string DefaultSuperArmorTagName = "State.Combat.SuperArmor";
    private const string DefaultInvincibilityTagName = "State.Combat.Invincibility";

    #region === Inspector ===

    [Header("References")]
    [SerializeField, Tooltip("Owning Actor. Resolved from the same GameObject when left empty.")]
    private Actor _actor;

    [SerializeField, Tooltip("Receives hit-event tags generated by incoming attacks.")]
    private ActionStateManager _asm;

    [Header("Health")]
    [SerializeField, Min(1f), Tooltip("Maximum health assigned on Awake.")]
    private float _maxHealth = 100f;

    [Header("Hit Reaction")]
    [SerializeField, Tooltip("When this actor has this tag, damage is still applied but hit-event reactions are suppressed. Falls back to State.Combat.SuperArmor when unassigned.")]
    private TagReference superArmorTag;

    [SerializeField, Tooltip("When this actor has this tag, incoming hits apply no damage and trigger no hit-event reaction. Falls back to State.Combat.Invincibility when unassigned.")]
    private TagReference invincibilityTag;

    [Header("Targeting")]
    [SerializeField, Min(0f), Tooltip("Radius used to find a soft auto target while not locked.")]
    private float autoAcquireRadius = 15f;

    [SerializeField, Min(0f), Tooltip("Radius used to keep or reacquire a target while locked.")]
    private float lockRetainRadius = 25f;

    [Header("Runtime State")]
    [SerializeField, Tooltip("Runtime lock mode. Change through the lock API during play.")]
    private Enums.LockMode lockMode = Enums.LockMode.None;

    [SerializeField, Tooltip("Runtime combat target resolved by auto-acquire or lock APIs.")]
    private GameObject combatTarget;

    [Header("Debug")]
    [SerializeField, Tooltip("Log damage and death events.")]
    private bool _debugLog = true;

    #endregion

    /*
     * Serialized field names are intentionally kept stable:
     * _maxHealth, _debugLog, _actor, _asm, autoAcquireRadius,
     * lockRetainRadius, lockMode, and combatTarget are referenced by Unity assets.
     */

    public GameObject CombatTarget => combatTarget;
    public Enums.LockMode LockMode => lockMode;
    public bool IsLocked => lockMode != Enums.LockMode.None;
    public float CurrentHealth => _currentHealth;
    public float MaxHealth => _maxHealth;
    public float HealthNormalized => _maxHealth > 0f ? Mathf.Clamp01(_currentHealth / _maxHealth) : 0f;
    public bool IsDead => _currentHealth <= 0f;

    public event Action<ActorCombater, float, float> HealthChanged;

    private float _currentHealth;

    private static readonly List<ActorCombater> _activeCombaters = new List<ActorCombater>();

    private void Awake()
    {
        if (_actor == null)
            _actor = GetComponent<Actor>();
        if (_asm == null)
            _asm = GetComponent<ActionStateManager>();
        _maxHealth = Mathf.Max(1f, _maxHealth);
        _currentHealth = _maxHealth;
    }

    private void OnEnable()
    {
        if (!_activeCombaters.Contains(this))
            _activeCombaters.Add(this);
    }

    private void OnDisable()
    {
        _activeCombaters.Remove(this);
    }

    private void OnDestroy()
    {
        _activeCombaters.Remove(this);
    }

    private void Update()
    {
        MaintainTarget();
    }

    #region === Target Acquisition ===

    private void MaintainTarget()
    {
        if (lockMode == Enums.LockMode.None)
        {
            combatTarget = FindBestAutoTarget()?.gameObject;
        }
        else
        {
            if (IsValidTarget(combatTarget, lockRetainRadius))
            {
                // keep current lock target
            }
            else if (TryFindBestLockFallback(out var fallback))
            {
                combatTarget = fallback;
            }
            else
            {
                ClearLock();
            }
        }
    }

    private ActorCombater FindBestAutoTarget()
    {
        ActorCombater best = null;
        float bestScore = float.MinValue;
        ActorCombater currentTarget = combatTarget != null ? combatTarget.GetComponent<ActorCombater>() : null;

        for (int i = _activeCombaters.Count - 1; i >= 0; i--)
        {
            ActorCombater candidate = _activeCombaters[i];
            if (candidate == null)
            {
                _activeCombaters.RemoveAt(i);
                continue;
            }

            if (!IsValidTarget(candidate.gameObject, autoAcquireRadius)) continue;

            float score = ScoreTarget(candidate, currentTarget, autoAcquireRadius);
            if (score > bestScore)
            {
                bestScore = score;
                best = candidate;
            }
        }

        return best;
    }

    private bool TryFindBestLockFallback(out GameObject fallback)
    {
        ActorCombater best = null;
        float bestScore = float.MinValue;

        for (int i = _activeCombaters.Count - 1; i >= 0; i--)
        {
            ActorCombater candidate = _activeCombaters[i];
            if (candidate == null)
            {
                _activeCombaters.RemoveAt(i);
                continue;
            }

            if (!IsValidTarget(candidate.gameObject, lockRetainRadius)) continue;

            float score = ScoreTarget(candidate, null, lockRetainRadius);
            if (score > bestScore)
            {
                bestScore = score;
                best = candidate;
            }
        }

        fallback = best != null ? best.gameObject : null;
        return fallback != null;
    }

    private bool IsValidTarget(GameObject target, float radius)
    {
        if (target == null) return false;
        if (!target.activeInHierarchy) return false;
        if (target == gameObject) return false;

        ActorCombater combater = target.GetComponent<ActorCombater>();
        if (combater == null) return false;
        if (!combater.enabled) return false;

        float dist = Vector3.Distance(transform.position, target.transform.position);
        return dist <= radius;
    }

    private float ScoreTarget(ActorCombater candidate, ActorCombater currentTarget, float scoreRadius)
    {
        Vector3 toTarget = candidate.transform.position - transform.position;
        float dist = toTarget.magnitude;

        // Distance score: closer is better (0 to 1 range)
        float distScore = 1f - Mathf.Clamp01(dist / Mathf.Max(0.001f, scoreRadius));

        // Forward facing bonus: prefer targets in front (0 to 0.5 range)
        Vector3 forward = transform.forward;
        Vector3 toTargetXZ = toTarget;
        forward.y = 0f;
        toTargetXZ.y = 0f;
        float angleScore = 0f;
        if (toTargetXZ.sqrMagnitude > 0.001f)
        {
            float dot = Vector3.Dot(forward.normalized, toTargetXZ.normalized);
            angleScore = (dot + 1f) * 0.25f;
        }

        // Current target retention bonus
        float retainBonus = (currentTarget != null && candidate == currentTarget) ? 0.3f : 0f;

        return distScore + angleScore + retainBonus;
    }

    #endregion

    #region === Lock Control API ===

    public bool TryEnterSoftLock()
    {
        if (lockMode != Enums.LockMode.None) return false;

        GameObject target = IsValidTarget(combatTarget, lockRetainRadius)
            ? combatTarget
            : FindBestAutoTarget()?.gameObject;
        if (target == null) return false;

        combatTarget = target;
        lockMode = Enums.LockMode.SoftLock;
        return true;
    }

    public bool TryEnterHardLock()
    {
        if (lockMode == Enums.LockMode.HardLock) return false;

        GameObject target = IsValidTarget(combatTarget, lockRetainRadius)
            ? combatTarget
            : FindBestAutoTarget()?.gameObject;
        if (target == null) return false;

        combatTarget = target;
        lockMode = Enums.LockMode.HardLock;
        return true;
    }

    public void ClearLock()
    {
        lockMode = Enums.LockMode.None;
        combatTarget = FindBestAutoTarget()?.gameObject;
    }

    public void ToggleSoftLock()
    {
        if (lockMode == Enums.LockMode.SoftLock)
            ClearLock();
        else
            TryEnterSoftLock();
    }

    #endregion

    #region === Damage / Hit Events ===

    public HitResolveResult TakeDamage(AttackHitData attackData)
    {
        if (HasInvincibility())
        {
            if (_debugLog)
                Debug.Log($"[Hit Reaction] {name} is invincible. Damage and hit reaction suppressed.");
            return HitResolveResult.Invincible();
        }

        float previousHealth = _currentHealth;
        _currentHealth = Mathf.Clamp(_currentHealth - attackData.Damage, 0f, _maxHealth);
        if (!Mathf.Approximately(previousHealth, _currentHealth))
            NotifyHealthChanged();

        bool hitReactionApplied = ApplyHitEventTag(attackData);

        if (_debugLog)
        {
            string attackerName = attackData.Attacker != null ? attackData.Attacker.name : "Unknown";
            Debug.Log($"[受到伤害] 来源: {attackerName}, " +
                     $"伤害: {attackData.Damage}, " +
                     $"剩余生命: {_currentHealth}/{_maxHealth}");
        }

        if (_currentHealth <= 0)
        {
            Die(attackData);
        }

        return HasSuperArmor()
            ? HitResolveResult.SuperArmor()
            : HitResolveResult.Normal(hitReactionApplied);
    }

    private void Die(AttackHitData attackData)
    {
        string attackerName = attackData.Attacker != null ? attackData.Attacker.name : "Unknown";
        if (_debugLog) Debug.Log($"[死亡] {name} 被 {attackerName} 击败");
        gameObject.SetActive(false);
    }

    private void NotifyHealthChanged()
    {
        HealthChanged?.Invoke(this, _currentHealth, _maxHealth);
    }

    private bool ApplyHitEventTag(AttackHitData attackData)
    {
        if (attackData.HitEventTag == null)
            return false;

        if (HasSuperArmor())
        {
            if (_debugLog)
                Debug.Log($"[Hit Reaction] {name} has super armor. Damage applied, hit reaction suppressed.");
            return false;
        }

        if (_asm != null)
        {
            var context = new ActionEventContext
            {
                Instigator = attackData.Attacker != null ? attackData.Attacker.gameObject : null,
                Target     = gameObject,
                HitPoint   = attackData.HitPoint,
                Direction  = attackData.Attacker != null
                    ? (transform.position - attackData.Attacker.transform.position).normalized
                    : Vector3.zero,
                Magnitude  = attackData.Damage
            };
            _asm.SendEvent(attackData.HitEventTag, context);
            return true;
        }

        return false;
    }

    private bool HasSuperArmor()
    {
        Tag tag = ResolveSuperArmorTag();
        return HasActorTag(tag);
    }

    private bool HasInvincibility()
    {
        Tag tag = ResolveInvincibilityTag();
        return HasActorTag(tag);
    }

    private bool HasActorTag(Tag tag)
    {
        if (_actor == null || tag == null)
            return false;

        return _actor.HasTag(tag, ActorTagContainerType.Transient, ActorTagMatchMode.Exact) ||
               _actor.HasTag(tag, ActorTagContainerType.Persistent, ActorTagMatchMode.Exact);
    }

    private Tag ResolveSuperArmorTag()
    {
        Tag tag = superArmorTag != null ? superArmorTag.GetTag() : null;
        return tag ?? Tag.GetTagFromFullName(DefaultSuperArmorTagName);
    }

    private Tag ResolveInvincibilityTag()
    {
        Tag tag = invincibilityTag != null ? invincibilityTag.GetTag() : null;
        return tag ?? Tag.GetTagFromFullName(DefaultInvincibilityTagName);
    }

    #endregion
}

public partial class Enums
{
    public enum LockMode
    {
        None, SoftLock, HardLock
    }
}
